### ISSUE TITLE
Check if all rests have consistent names 

### ISSUE THREAD

**Issue by sertansenturk** [MTG/SymbTr#12]
even though all the "Sus" and "Es" might have been merged in v2.2, there might still be letfover or rests indicated with an empty string. Make an automatic checker for it.

**Comment by burakuyar** [comment]
In the symbtr documentation (excel file), it is stated that the Kod0 indicates rests. However, almost all rests have Kod9 in txt files. Is this something to be fixed in the files or ini the excel doc?

**Comment by sertansenturk** [comment]
Good point! The current [version](https://github.com/MTG/SymbTr/blob/master/code_explanations.xlsx) says  Kod9 is also for rests. I have to consult it with Kemal. But since all the rests have Kod9 in the collection (it's being checked after [symbtrdataextractor/commit/c9a31d0f73654f11b926334880656bc6f4a5dee7](https://github.com/sertansenturk/symbtrdataextractor/commit/c9a31d0f73654f11b926334880656bc6f4a5dee7) called by [extras/unittests/validatetxtcontent.py](https://github.com/MTG/SymbTr/blob/3866898fc38023ee6abc4e680809d81925dfd523/extras/unittests/validatetxtcontent.py) using travis ci), we can safely assume Kod9 is correct for rests.
