### ISSUE TITLE
Invalid MusicXML files

### ISSUE THREAD

**Issue by dspreadbury** [MTG/SymbTr#2]
Thank you very much for making this corpus of data available!

However, all of the MusicXML files I have tried to open so far are showing significant validation errors. I don't know how the MusicXML files are being generated (they lack any information about the software that created/encoded them), but it would appear that whatever software is being used to export MusicXML versions of these files needs some serious attention to improve the validity of the MusicXML files being exported.

**Comment by burakuyar** [comment]
Many thanks for your feedback @dspreadbury . Soon, we are actually going to re-implement the code. However, the issue you have stated is one of the things we could not find an answer yet. Do you know if there is a tool or procedure to check the validity of a MusicXML file?

**Comment by dspreadbury** [comment]
Most XML editors (e.g. [OxygenXML](http://www.oxygenxml.com/xml_editor/validation.html) and the like) have tools for validating a MusicXML file against a schema. You can also use an online tool, such as [this one](http://www.freeformatter.com/xml-validator-xsd.html). If you upload the **musicxml.xsd** file from inside [musicxml30.zip](http://www.musicxml.com/wp-content/uploads/2012/11/musicxml30.zip) to a publicly accessible URL (e.g. a public folder in Dropbox), you can paste the URL into the **XSD input** box, and the URL to the "raw" version of any of your MusicXML files (e.g. [this one](https://raw.githubusercontent.com/MTG/SymbTr/master/MusicXML/acem--ilahi--duyek--aldanma_dunya--zekai_dede.xml)) into the **XML input** box, and you will then be able to see the validation errors in detail.

It turns out that the majority of the validation errors in your MusicXML files are caused by two problems: firstly, in the `<attributes>` element in the first bar, the key signature (the `<key>` element) follows the time signature (the `<time>` element), which is wrong: the time signature must precede the key signature. Secondly, you use an empty accidental element (i.e. `<accidental/>`), which is invalid: the `<accidental>` element must contain a valid [accidental-value](http://www.musicxml.com/UserManuals/MusicXML/MusicXML.htm#ST-MusicXML-accidental-value.htm), and cannot be empty.

If your MusicXML files are being generated by a specific software package, it would be worth contacting the developers of that package to ask them to look into these validation errors and to fix their code.
