### ISSUE TITLE
Uncommon note duration

### ISSUE THREAD

**Issue by burakuyar** [MTG/SymbTr#26]
I noticed a note with duration 11/32 in the piece below. In the pdf this note is displayed as two seperate notes, 3/32, 8/32. I couldn't understand whether the value 11 indicates any other valuable information.

Assuming the value 11 doesn't provide any other information, should this note be divided into two seperate notes in the txt lib or should I handle this as I did for the pay values 5 and 7?

muhayyer--bozlak--sofyan--havayi_da--asaf_guven
82  9   Do5 C5  318 318 11  32  1375    100 96      9.000000

**Comment by sertansenturk** [comment]
Judging from the pdf, that note and the previous note is written incorrectly. Also notice that the durations in the pdf would overflow that measure.

Better to ask Kemal this Friday.
