### ISSUE TITLE
Mu2 Format

### ISSUE THREAD

**Issue by ihpar** [MTG/SymbTr#54]
Hi there,
I'm trying to understand mu2 file format. Do you have any sources? I think I understood most of it by eye but there are some symbols and numbers which I cannot understand.
Thank you very much for the dataset.
Best regards

**Comment by mus2alfa** [comment]
There is a document about it. But unfortunately some parts of it is in Turkish. I hope this helps. [https://drive.google.com/file/d/1tQEcmZgELUKePJ9FSDhRID-EAgq4zFtQ/view?usp=sharing](https://drive.google.com/file/d/1tQEcmZgELUKePJ9FSDhRID-EAgq4zFtQ/view?usp=sharing)

**Comment by ihpar** [comment]
@mus2alfa Wow! Thank you very much! It's very informative.
Best regards
